services:

  postgres:
    image: postgres:16-alpine
    container_name: order-engine-postgres

    environment:
      POSTGRES_DB: order-engine-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: order-engine-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-engine:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: order-engine-app

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order-engine-dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

volumes:
  postgres_data:
  redis_data: